# Generated by Django 4.2.1 on 2024-04-02 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetravelallowance',
            name='contact_person_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employeetravelallowance',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
