# Generated by Django 4.2.1 on 2024-03-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetravelallowance',
            name='km_covered',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='employeetravelallowance',
            name='location_from',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='employeetravelallowance',
            name='location_to',
            field=models.CharField(max_length=255),
        ),
    ]
